// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import Image from './Image';
import Logo from './Logo';
import MainMenu from './MainMenu';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Hero,
	Image,
	Logo,
	MainMenu,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	hero: Hero,
	image: Image,
	logo: Logo,
	main_logo: MainMenu,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
