// This file is generated by Slice Machine. Update with care!

import AboutTextWithButton from './AboutTextWithButton';
import FloatingImage from './FloatingImage';
import Footer from './Footer';
import Hero from './Hero';
import Image from './Image';
import LanguageSelector from './LanguageSelector';
import Logo from './Logo';
import LogoMarquee from './LogoMarquee';
import MainMenu from './MainMenu';
import Mansory from './Mansory';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';
import TopBar from './TopBar';

export {
	AboutTextWithButton,
	FloatingImage,
	Footer,
	Hero,
	Image,
	LanguageSelector,
	Logo,
	LogoMarquee,
	MainMenu,
	Mansory,
	TextWithFeatures,
	TextWithImage,
	TopBar,
};

export const components = {
	about_text_with_button: AboutTextWithButton,
	floating_image: FloatingImage,
	footer: Footer,
	hero: Hero,
	image: Image,
	language_selector: LanguageSelector,
	logo: Logo,
	logo_marquee: LogoMarquee,
	main_logo: MainMenu,
	mansory: Mansory,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
	top_bar: TopBar,
};
